### ISSUE TITLE
Loader: Illegal base64 character 2e

### ISSUE THREAD

**Issue by turbaszek** [snowplow-incubator/snowplow-bigquery-loader#112] opened 2020-07-12 12:14 UTC
Hi all,

I am trying to run bigquery loader as k8s job:
```yml
...
containers:
        - image: snowplow-docker-registry.bintray.io/snowplow/snowplow-bigquery-loader:0.5.0
          imagePullPolicy: IfNotPresent
          name: bq-loader
          args:
            - --config=/snowplow/customconfig/config/production.conf
            - --resolver=/snowplow/customconfig/resolver/resolver.json
...
```
I configured the topis/subscriptions as per https://docs.snowplowanalytics.com/docs/setup-snowplow-on-gcp/setup-bigquery-destination/bigquery-loader-0-5-0/#topics-and-message-formats

However, there's an error with no stack trace:
```
{
 insertId:  "g4r5w3es15d1dlm7e"   
 labels: {…}   
 logName:  "projects/PROJECT/logs/stderr"   
 receiveTimestamp:  "2020-07-12T11:58:09.421811185Z"   
 resource: {
  labels: {…}    
  type:  "k8s_container"    
 }
 severity:  "ERROR"   
 textPayload:  "Illegal base64 character 2e
"   
 timestamp:  "2020-07-12T11:57:57.447664061Z"   
}
```

Any ideas what can cause it?

**Comment by turbaszek** [comment] 2020-07-12 12:15
@chuwy @dilyand

**Comment by chuwy** [comment] 2020-07-12 12:46
Hi @turbaszek! The problem is that jobs expect config files passed as base64-encoded strings. Here's the same error for Snowflake Loader: https://discourse.snowplowanalytics.com/t/configuring-the-playbook-json-for-loading-snowflake/1814.

In future please refer to our [Discourse forums](https://discourse.snowplowanalytics.com/) if you need help with pipeline - we're using GitHub for bug reports and feature requests only. 

Closing this one.

**Closed by chuwy** 2020-07-12 12:46 UTC

**Comment by turbaszek** [comment] 2020-07-12 14:02
Thanks! It seems to be a bug unresolved for last few months:
https://discourse.snowplowanalytics.com/t/illegal-base64-character-when-running-bigquery-mutator-with-docker/3662
